server {
    listen 8080;
    server_name localhost mysite.com;
    root test_page/login;
    error_page 404 404.html;

    # location 1
    location / {
        root test_page/login;
        methods GET POST DELETE;
        index index.php;
        uploadDir /home/necro/Desktop/webserv/test_pages/login/uploads;
        clientMaxBodySize 2MB;
        hasClientMaxBodySize true;
        cgi {
            .php /usr/bin/php-cgi;
        }
    }
}
