server {
    listen 8080;
    server_name localhost mysite.com;
    root test_page/login;
    client_max_body_size 1MB;

    # location 1
    location / {
        root test_page/login;
        methods GET POST DELETE;
        index index.php;
        autoindex on;
        uploadDir /home/necro/Desktop/webserv/test_pages/login/uploads;
        clientMaxBodySize 512KB;
        hasClientMaxBodySize true;
        cgi {
            .php /usr/bin/php-cgi;
        }
    }
}
