server {
    listen 8081;
    root YoupiBanane;

	cgi {
		.bla /path
	}

    location / {
        methods GET;
        autoindex on;
    }

    location / {
        methods POST;
        cgi {
            .bla ./cgi_tester;
        }
    }

    location /post_body {
        methods POST;
        clientMaxBodySize 100;
    }

    location /directory {
        methods GET;
        root YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
        cgi {
            .bla ./cgi_tester;
        }
    }
}
