server {
    listen 8080;
    root YoupiBanane/;

    location / {
        root YoupiBanane/;
        methods GET;
        autoindex on;

        cgi {
            .bla /home/necro/Downloads/cgi_tester;
        }
    }

    location /post_body {
        methods POST;
        clientMaxBodySize 100B;
        cgi {
            .bla /home/necro/Downloads/cgi_tester;
        }
    }

    location /directory {
        root YoupiBanane/;
        methods GET;
        index youpi.bad_extension;
        cgi {
            .bla /home/necro/Downloads/cgi_tester;
        }
    }
}
